spring:
    mvc:
        log-request-details: true
    datasource:
        #url: jdbc:h2:./testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
        url: jdbc:h2:mem:bookdb;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    sql:
        init:
            #mode: never
            mode: always
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: true
        show-sql: true
        generate-ddl: true
        defer-datasource-initialization: true
        #hibernate:
            #ddl-auto: create
    h2:
        console:
            enabled: true
    liquibase:
        enabled: false
        change-log: classpath:liquibase/changelog.xml

    security:
        user:
            name: user
            password: pass
        oauth2:
            client:
                registration:
                    google:
                        # client mit redirect-uri *:8080 und *:8081
                        client-id: 215038427959-onpg4hmdlbh6570gq98aji22hi35f3gs.apps.googleusercontent.com
                        client-secret: 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

logging:
    level:
        "[de.workshops]": debug
        web: debug
        "[org.springframework.web]": debug
        #"[org.hibernate.type]": trace

springdoc:
    api-docs:
        enabled: false

myapp:
    int-param: 42
    string-param: test

---
spring:
    config:
        activate:
            on-profile:
                - prod
server:
    port: 8081

