spring:
    mvc:
        log-request-details: true
    datasource:
        #url: jdbc:h2:./testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
        url: jdbc:h2:mem:bookdb;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    sql:
        init:
            mode: never
            #mode: always
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: true
        show-sql: true
        #generate-ddl: true
        #defer-datasource-initialization: true
        #hibernate:
            #ddl-auto: create
    h2:
        console:
            enabled: true
    liquibase:
        enabled: true
        change-log: classpath:liquibase/changelog.xml

logging:
    level:
        "[de.workshops]": debug
        web: debug
        "[org.springframework.web]": debug
        #"[org.hibernate.type]": trace

springdoc:
    api-docs:
        enabled: false

myapp:
    int-param: 42
    string-param: test

---
spring:
    config:
        activate:
            on-profile:
                - prod
server:
    port: 8081

