spring:
    mvc:
        log-request-details: true
    test:
        mockmvc:
            print: LOG_DEBUG
logging:
    level:
        "[de.workshops]": debug
        web: debug
        "[org.springframework.web]": debug

